requires 'perl', '5.22.0';

on 'develop' => sub {
	requires 'App::cpm';
	requires 'CPAN::Uploader';
	requires 'Data::Printer', '1.000004';
	requires 'Minilla', 'v3.1.19';
	requires 'Liveman', '1.0';
	requires 'Software::License::GPL_3';
	requires 'Test::CPAN::Meta';
	requires 'Test::MinimumVersion::Fast';
	requires 'Test::PAUSE::Permissions';
	requires 'Test::Pod';
	requires 'Test::Spellunker';
	requires 'V';
	requires 'Version::Next';
};

on 'test' => sub {
	requires 'Carp';
	requires 'Cwd';
	requires 'Data::Dumper';
	requires 'File::Basename';
	requires 'File::Find';
	requires 'File::Path';
	requires 'File::Slurper';
	requires 'File::Spec';
	requires 'Scalar::Util';
	requires 'String::Diff';
	requires 'Term::ANSIColor';
	requires 'Test::More';
	requires 'lib';
	requires 'open';
};

requires 'Aion', '1.7';
requires 'Aion::Annotation';
requires 'Aion::Carp';
requires 'Aion::Emitter', '0.1.0';
requires 'Aion::Format';
requires 'Aion::Format::Html';
requires 'Aion::Format::Json';
requires 'Aion::Format::Yaml';
requires 'Aion::Run';
requires 'B::Deparse';
requires 'Coro';
requires 'Coro::AnyEvent';
requires 'Coro::LWP';
requires 'Coro::Semaphore';
requires 'Corona::Server';
requires 'Devel::StackTrace::AsHTMLExtended';
requires 'Eon::Html::Ed';
requires 'Guard';
requires 'HTTP::Exception';
requires 'HTTP::Status';
requires 'LWP::UserAgent';
requires 'MIME::Types';
requires 'Net::Server::Proto::UNIX';
requires 'POSIX';
requires 'Parse::ErrorString::Perl';
requires 'Plack::Request';
requires 'Time::HiRes';
requires 'URI';
requires 'bytes';
requires 'common::sense';
requires 'config';
