name = "Aion-Action"

authority="cpan:DART"
license="gpl_3"

module_maker="ModuleBuildTiny"
badges = ["github-actions/test.yml"]
static_install = "auto"
markdown_maker = "Liveman::MinillaPod2Markdown"
